---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.example.com"
  dnsNames:
  - "*.example.com"
