# eda.yaml
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda
spec:
  automation_server_url: http://192.168.1.119:30080 # Host or FQDN of AWX
  service_type: nodeport
  nodeport_port: 30081
  image: quay.io/ansible/eda-server
  image_version: sha-70529ad

  # Use fixed version of eda-ui
  image_web: quay.io/ansible/eda-ui
  image_web_version: 2.4.716

  # Trust internal origin for eda-api
  extra_settings:
    - setting: EDA_CSRF_TRUSTED_ORIGINS
      value: http://eda-api:8000