apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/eda-server-operator/config/default?ref=0.0.4
  - eda.yml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/eda-server-operator
    newTag: 0.0.4

# Specify a custom namespace in which to install EDA
namespace: eda