---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.9.0
  - awx.yml
#  - awx-pv.yml
#  - awx-pvc.yml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.9.0

namespace: awx